version: "3"
services:
  ui:
    build: .
    network_mode: "host"
    environment:
      - DISPLAY
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./gtfs:/gtfs

